services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - "5432:5432"
    networks:
      - sb-emulator
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 15s
      retries: 10
  mssql:
        container_name: "mssql"
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        networks:
          - sb-emulator
        environment:
          ACCEPT_EULA: ${ACCEPT_EULA}
          MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
  servicebus:
    container_name: "servicebus"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5671:5671"
      - "5672:5672"
      - "5300:5300"
      - "8080:8080"
      - "80:80" 
    restart: always
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: ${ACCEPT_EULA}
      SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL}
    depends_on:
      mssql:
        condition: service_started
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  api:
    build:
      context: ./
      dockerfile: ./src/ConsultaCreditoService.Api/Dockerfile
    ports:
      - "5025:8080"
    networks:
      - sb-emulator
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      servicebus:
        condition: service_started
    environment:
      ConnectionStrings__Database: "${DB_CONNECTION_STRING}"
      AzureServiceBus__ConnectionString: "${SERVICE_BUS_CONNECTION_STRING}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5025/ready"]
      interval: 10s
      timeout: 15s
      retries: 5
  worker:
    build:
      context: ./
      dockerfile: ./src/ConsultaCreditoService.Worker/Dockerfile
    networks:
      - sb-emulator
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      servicebus:
        condition: service_started
    environment:
      ConnectionStrings__Database: "${DB_CONNECTION_STRING}"
      AzureServiceBus__ConnectionString: "${SERVICE_BUS_CONNECTION_STRING}"
networks:
  sb-emulator:
    driver: bridge