services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - "5432:5432"
    networks:
      - sb-emulator
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
  servicebus:
    container_name: "servicebus"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5671:5671"
      - "5672:5672"
      - "5300:5300"
      - "8080:8080"
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: ${ACCEPT_EULA}
      SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL}
    depends_on:
      - mssql
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  mssql:
        container_name: "mssql"
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        networks:
          sb-emulator:
            aliases:
              - "mssql"
        environment:
          ACCEPT_EULA: ${ACCEPT_EULA}
          MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}" # To be filled by user as per policy : https://learn.microsoft.com/en-us/sql/relational-databases/security/strong-passwords?view=sql-server-linux-ver16 
  api:
    build:
      context: ./
      dockerfile: ./src/ConsultaCreditoService.Api/Dockerfile
    ports:
      - "5025:8080"
    networks:
      - sb-emulator
    depends_on:
      postgres:
        condition: service_healthy 
    environment:
      ConnectionStrings__Database: "${DB_CONNECTION_STRING}"
      AzureServiceBus__ConnectionString: "${SERVICE_BUS_CONNECTION_STRING}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
      interval: 5s
      retries: 10
  worker:
    build:
      context: ./
      dockerfile: ./src/ConsultaCreditoService.Worker/Dockerfile
    networks:
      - sb-emulator
    depends_on:
      - servicebus
      - api
    environment:
      ConnectionStrings__Database: "${DB_CONNECTION_STRING}"
      AzureServiceBus__ConnectionString: "${SERVICE_BUS_CONNECTION_STRING}"
networks:
  sb-emulator:
    driver: bridge